# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awa < Formula
  desc "Awa Finance CLI"
  homepage "https://awafinance.com"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.awafinance.com/v0.2.1/awa_Darwin_x86_64.tar.gz"
      sha256 "4c4978a4d5480236e370a9868a9a752dafa714795f108168e8e26e795723f8c6"

      def install
        bin.install "awa"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.awafinance.com/v0.2.1/awa_Darwin_arm64.tar.gz"
      sha256 "251d64757c0c747d9aa2ff1762215d18b2e077b607d7aabd8229b3a7acf0b9ce"

      def install
        bin.install "awa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://releases.awafinance.com/v0.2.1/awa_Linux_x86_64.tar.gz"
      sha256 "921c1afcd252adac49baee5dcdfa76186e1eb5326e9439b4125cf883ca8c8e83"
      def install
        bin.install "awa"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://releases.awafinance.com/v0.2.1/awa_Linux_arm64.tar.gz"
      sha256 "ac174ff0571f38c3a8c355b6ba63ea3eecc14e04cfa81eddc715c35bebac255e"
      def install
        bin.install "awa"
      end
    end
  end
end
