# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwaCli < Formula
  desc "Awa Finance CLI"
  homepage "https://awafinance.com"
  version "0.2.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.awafinance.com/v0.2.6/awa_Darwin_x86_64.tar.gz"
      sha256 "ed9d8ff0ff42cd03c77ca8e87cec1a7df3095f370f020935d8d71d7f8cc39220"

      define_method(:install) do
        bin.install "awa"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.awafinance.com/v0.2.6/awa_Darwin_arm64.tar.gz"
      sha256 "d72f1e8e6564e6ad6aecb4bdd10ba58bd04d1c96a19ab9b1c21506990052c191"

      define_method(:install) do
        bin.install "awa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.awafinance.com/v0.2.6/awa_Linux_x86_64.tar.gz"
      sha256 "791ff9e933cab72b7c30275c83279fdebf42e1848c8e79f4756da51780c8f716"
      define_method(:install) do
        bin.install "awa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.awafinance.com/v0.2.6/awa_Linux_arm64.tar.gz"
      sha256 "a5f40c97b56bb576cb6986312a1f5a0ab108f93fcdbbe95d6baec6d4c1a1704f"
      define_method(:install) do
        bin.install "awa"
      end
    end
  end
end
