# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwaCli < Formula
  desc "Awa Finance CLI"
  homepage "https://awafinance.com"
  version "0.2.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.awafinance.com/v0.2.11/awa_Darwin_x86_64.tar.gz"
      sha256 "ee3776bc6a8007b0e97803c1ca965336b2962667c0a49f8cce835faa3169931d"

      define_method(:install) do
        bin.install "awa"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.awafinance.com/v0.2.11/awa_Darwin_arm64.tar.gz"
      sha256 "dbcbabc698ca5661718e55f577b1dfb1e1b4a3656e69e64c95654a256a88177d"

      define_method(:install) do
        bin.install "awa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.awafinance.com/v0.2.11/awa_Linux_x86_64.tar.gz"
      sha256 "b180f3e6f279c6156cbd6df86e517bd96ee6de4996a4a60c9f12fd412d9afee6"
      define_method(:install) do
        bin.install "awa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.awafinance.com/v0.2.11/awa_Linux_arm64.tar.gz"
      sha256 "5c446dcd89263d428dad0666fc55f9d17f77797e686cf654f2af5601bd2f647c"
      define_method(:install) do
        bin.install "awa"
      end
    end
  end
end
