# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awa < Formula
  desc "Awa Finance CLI"
  homepage "https://awafinance.com"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.awafinance.com/v0.2.1/awa_Darwin_x86_64.tar.gz"
      sha256 "f8c814fa5353c1942ab7b0cef9985b9a38fe5df8b482d1e30844f34444a1b04d"

      define_method(:install) do
        bin.install "awa"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.awafinance.com/v0.2.1/awa_Darwin_arm64.tar.gz"
      sha256 "f28fc92658fb9d8c53de4d7dabd000c98b6969d589d14c5932f99b0cf39d0816"

      define_method(:install) do
        bin.install "awa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.awafinance.com/v0.2.1/awa_Linux_x86_64.tar.gz"
      sha256 "49025e0a7302563278d0bc0a25879a8d24e2f047457fa9e719a2162e053c6e23"
      define_method(:install) do
        bin.install "awa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.awafinance.com/v0.2.1/awa_Linux_arm64.tar.gz"
      sha256 "e1eec5e0a22bf0765c759632c9ebd0bd9beae6852b1b7b76c02d5405215822ba"
      define_method(:install) do
        bin.install "awa"
      end
    end
  end
end
